# Generated by Django 4.2.5 on 2023-09-13 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responses", models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name="option",
            name="question",
        ),
        migrations.AlterUniqueTogether(
            name="responses",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="responses",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="responses",
            name="question",
        ),
        migrations.RemoveField(
            model_name="responses",
            name="selected_option",
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="survey",
            name="description",
            field=models.TextField(default="Default Description"),
        ),
        migrations.DeleteModel(
            name="Candidate",
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="Responses",
        ),
        migrations.AddField(
            model_name="response",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.survey"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
