# Generated by Django 4.2.5 on 2023-09-13 17:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_response_remove_option_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question1_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question2_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question3_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question4_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question5_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question6_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question7_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question8_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question9_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question10_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question11_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question12_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question13_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question14_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question15_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question16_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question17_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question18_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question19_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
                (
                    "question20_response",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Response must be between 1 and 10"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "Response must be between 1 and 10"
                            ),
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="question",
            name="options",
        ),
        migrations.RemoveField(
            model_name="question",
            name="text",
        ),
        migrations.AddField(
            model_name="question",
            name="question10_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question11_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question12_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question13_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question14_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question15_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question16_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question17_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question18_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question19_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question1_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question20_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question2_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question3_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question4_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question5_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question6_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question7_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question8_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question9_answer",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Answer must be between 1 and 10"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, "Answer must be between 1 and 10"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="survey",
            name="survey_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="survey",
            name="description",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="Response",
        ),
        migrations.AddField(
            model_name="userresponse",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.survey"
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
